# @Author: yangwenhao
# @Contact: 874681044@qq.com
# @Software: PyCharm
# @File: aidata_resnet_mixup.yaml
# @Time: 2022/09/30 09:15
# @Overview:

data_root_dir: /home/yangwenhao/project/lstm_speaker_verification

## Dataset
seed: 123456
datasets: aidata
feat_type: klfb
loss: arcsoft
input_dim: 40
feat: !ref fb<input_dim>
subset: ''

train_dir: !ref <data_root_dir>/data/<datasets>/egs/<feat_type>/train<subset>_<feat>
train_test_dir: !ref <data_root_dir>/data/<datasets>/<feat_type>/test<subset>_<feat>
train_trials: trials
valid_dir: !ref <data_root_dir>/data/<datasets>/egs/<feat_type>/train_<feat>_valid
num_valid: 2
test_dir: !ref <data_root_dir>/data/<datasets>/<feat_type>/test_<feat>
trials: trials
input_norm: Mean

test_input: fix
log_scale: False
random_chunk: [ 200, 400 ]
chunk_size: 300
frame_shift: 300
extract: True
nj: 8
shuffle: False
batch_shuffle: False

feat_format: kaldi
remove_vad: True


### Training settings

epochs: 60

# optimizer
optimizer: sgd
lr_decay: 0
weight_decay: 0.0005
dampening: 0
nesterov: False
momentum: 0.9
accu_steps: 1


# Scheduler
patience: 3
milestones: [ 10,20,30,40 ]
scheduler: rop
lr: 0.1
base_lr: 0.00001
cos_sim: True

## model Setttings
embedding_model: !new:Define_Model.ResNet.ThinResNet
  input_dim: !ref <input_dim>
  input_norm: !ref <input_norm>
  block_type: 'seblock'
  downsample: 'k1'
  red_ratio: 2
  fast: none1
  stride: [ 2, 1 ]
  channels: [ 16, 32, 64, 128 ]
  dropout_p: 0.1
  avg_size: 5
  encoder_type: 'ASTP2'
  embedding_size: !ref <embedding_size>
  num_classes: 420
  activation: relu

classifier: !new:Define_Model.Loss.SoftmaxLoss.AdditiveMarginLinear
  feat_dim: !ref <embedding_size>
  num_classes: 420

model: ThinResNet
kernel_size:
alpha: 0
embedding_size: 256
batch_size: 256
dropout_p: 0.0
activation: relu
channels: 16,32,64,128
encoder_type: ASTP2

# loss
loss_ratio: 1
lr_ratio: 0
loss_lambda: False
loss_type: !ref <loss>
margin: 0.2
# m: 0.2
s: 30
lamda_beta: 0.2
mixup_type: input
# stat_type: margin1

# Checkpoints
loss_str: ''
check_path: !ref Data/checkpoint/<model>_dist/<datasets>/<feat_type>_egs<subset>_baseline/<loss>_<optimizer>_<scheduler>/<input_norm>_<encoder_type>_em<embedding_size><loss_str>_wd5e4_vares_mixup<lamda_beta>_<mixup_type>/<seed>
resume: !ref <check_path>/checkpoint_40.pth

veri_pairs: 9600
gpu_id: 0,1


test_interval: 4
log_interval: 10