# @Author: yangwenhao
# @Contact: 874681044@qq.com
# @Software: PyCharm
# @File: aidata_resnet.yaml
# @Time: 2022/09/30 09:15
# @Overview:

data_root_dir: /home/yangwenhao/project/lstm_speaker_verification

## Dataset
seed: 123456
datasets: aidata
feat_type: klfb
loss: arcsoft
input_dim: 40
feat: !ref fb<input_dim>
subset: ""

train_dir: !ref <data_root_dir>/data/<datasets>/<feat_type>/train<subset>_<feat>
train_test_dir: !ref <data_root_dir>/data/<datasets>/<feat_type>/test<subset>_<feat>
train_trials: trials_4w
valid_dir: !ref <data_root_dir>/data/<datasets>/egs/<feat_type>/train_<feat>_valid
num_valid: 2
test_dir: !ref <data_root_dir>/data/<datasets>/<feat_type>/test_<feat>
trials: trials
input_norm: Inst
input_per_spks: 512

test_input: fix
log_scale: False
random_chunk: [300, 300]
chunk_size: 300
frame_shift: 300
num_frames: 300

extract: True
nj: 6
shuffle: False
batch_shuffle: True

feat_format: kaldi
remove_vad: True

### Training settings
epochs: 60

# optimizer
optimizer: sgd
lr_decay: 0
weight_decay: 0.0005
dampening: 0
nesterov: False
momentum: 0.9
accu_steps: 1

# Scheduler
patience: 3
milestones: [10, 20, 30, 40]
scheduler: rop
lr: 0.1
base_lr: 0.00001
cos_sim: True

early_stopping: True
early_patience: 15
early_delta: 0.0001
early_meta: "mix2"

## model Setttings
resnet_size: 10
block_type: "cbam"
red_ratio: 2
encoder_type: "SAP2"
downsample: "k3"
model: ThinResNet
kernel_size:
alpha: 0
avg_size: 5
embedding_size: 256
batch_size: 128
dropout_p: 0.1
activation: relu
channels: 16,32,64,128
fast: none1
num_classes: 420

embedding_model: !new:Define_Model.ResNet.ThinResNet
  resnet_size: !ref <resnet_size>
  input_dim: !ref <input_dim>
  input_norm: !ref <input_norm>
  block_type: !ref <block_type>
  downsample: !ref <downsample>
  red_ratio: !ref <red_ratio>
  fast: !ref <fast>
  alpha: !ref <alpha>
  stride: [2, 1]
  channels: [16, 32, 64, 128]
  dropout_p: !ref <dropout_p>
  avg_size: !ref <avg_size>
  encoder_type: !ref <encoder_type>
  embedding_size: !ref <embedding_size>
  num_classes: 420
  activation: relu

classifier: !new:Define_Model.Loss.SoftmaxLoss.AdditiveMarginLinear
  feat_dim: !ref <embedding_size>
  num_classes: 420

# loss
loss_ratio: 1
lr_ratio: 0
loss_lambda: False
loss_type: !ref <loss>
margin: 0.2
# m: 0.2
s: 30
lamda_beta: 0.2
mixup_type: input
# stat_type: margin1

# Checkpoints
loss_str: ""
check_path: !ref Data/checkpoint/<model><resnet_size>/<datasets>/<feat_type><subset>_baseline/<loss>_<optimizer>_<scheduler>/<input_norm>_batch<batch_size>_<block_type>_down<downsample>_avg<avg_size>_<encoder_type>_em<embedding_size>_dp01_alpha<alpha>_<fast>_wd5e4_varesmix2_bashuf2_dist/baseline_cm
#_mixup<lamda_beta>_<mixup_type>
resume: !ref <check_path>/checkpoint_40.pth

veri_pairs: 9600
gpu_id: 0,1

test_interval: 4
log_interval: 10
