# @Author: yangwenhao
# @Contact: 874681044@qq.com
# @Software: PyCharm
# @File: vox1_tdnn.yaml
# @Time: 2022/4/21 00:33
# @Overview:

data_root_dir: /home/yangwenhao/project/lstm_speaker_verification

## Dataset
datasets: cnceleb
feat_type: klfb
loss: arcsoft
input_dim: 40
feat: !ref fb<input_dim>
subset:

train_dir: !ref <data_root_dir>/data/<datasets>/egs/<feat_type>/dev<subset>_<feat>
train_test_dir: !ref <data_root_dir>/data/<datasets>/<feat_type>/dev<subset>_<feat>/trials_dir
train_trials: trials_2w
valid_dir: !ref <data_root_dir>/data/<datasets>/egs/<feat_type>/dev<subset>_<feat>_valid
num_valid: 2
test_dir: !ref <data_root_dir>/data/<datasets>/<feat_type>/test_<feat>
nj: 12
shuffle: False
feat_format: kaldi
remove_vad: True


# Training settings
epochs: 60
patience: 3
milestones: 10,20,30,40
optimizer: sgd
scheduler: rop
weight_decay: 0.0005
lr: 0.001
base_lr: 0.00000001
cos_sim: True

# model Setttings
model: TDNN_v5
input_norm: Mean
alpha: 0
embedding_size: 512
batch_size: 128
dropout_p: 0.0
random_chunk: [ 200, 400 ]
activation: leakyrelu
channels: 512,512,512,512,1500
encoder_type: STAP

# loss
loss_ratio: 1
lr_ratio: 0
loss_lambda: False
loss_type: !ref <loss>
margin: 0.2
#m: 0.2
s: 30
#stat_type: margin1

# Checkpoints
loss_str: ''
check_path: !ref Data/checkpoint/<model>/<datasets>/<feat_type>_egs<subset>_baseline/<loss>_<optimizer>_<scheduler>/<input_norm>_<encoder_type>_em<embedding_size><loss_str>_wd5e4_var
resume: !ref <check_path>/checkpoint_40.pth

veri_pairs: 9600
gpu_id: 2


log_interval: 10