# @Author: yangwenhao
# @Contact: 874681044@qq.com
# @Software: PyCharm
# @File: cnc1_tdnn.yaml
# @Time: 2022/4/21 00:33
# @Overview:

data_root_dir: /home/yangwenhao/project/lstm_speaker_verification

## Dataset
datasets: vox2
testset: vox1
feat_type: klfb
loss: arcsoft
input_dim: 40
feat: !ref fb<input_dim>
subset: ''

train_dir: !ref <data_root_dir>/data/<datasets>/egs/<feat_type>/dev<subset>_<feat>
train_test_dir: !ref <data_root_dir>/data/<testset>/<feat_type>/test<subset>_<feat>
train_trials: trials
valid_dir: !ref <data_root_dir>/data/<datasets>/egs/<feat_type>/dev<subset>_<feat>_valid
num_valid: 2
test_dir: !ref <data_root_dir>/data/<testset>/<feat_type>/test_<feat>
trials: trials
input_norm: Mean


test_input: fix
log_scale: False
random_chunk: [ 200, 200 ]
chunk_size: 300
frame_shift: 300
extract: True
nj: 4
shuffle: False
batch_shuffle: True
feat_format: kaldi
remove_vad: True


### Training settings
epochs: 60

# optimizer
optimizer: adam
lr: 0.001
base_lr: 0.00000001
lr_decay: 0
weight_decay: 0.00001
dampening: 0
momentum: 0.9
accu_steps: 1
nesterov: False

early_stopping: True
early_patience: 15
early_delta: 0.01
early_meta: 'EER'

# Scheduler
scheduler: cyclic
patience: 3
milestones: [ 10,20,30,40 ]
cyclic_epoch: 2
cos_sim: True

## model Setttings
model: ECAPA
kernel_size:
alpha: 0
embedding_size: 192
batch_size: 128
dropout_p: 0.0
activation: relu
channels: 512,512,512,512,1500
encoder_type: STAP

embedding_model: !new:Define_Model.TDNN.ECAPA_TDNN.ECAPA_TDNN
  input_dim: !ref <input_dim>
  input_norm: !ref <input_norm>
  channels: [ 512,512,512,512,1536 ]
  encoder_type: 'SASP2'
  embedding_size: !ref <embedding_size>
  num_classes: 5994
  activation: relu

classifier: !new:Define_Model.Loss.SoftmaxLoss.AdditiveMarginLinear
  feat_dim: !ref <embedding_size>
  num_classes: 5994

# loss
loss_ratio: 1
lr_ratio: 0
loss_lambda: False
loss_type: !ref <loss>
margin: 0.2
# m: 0.2
s: 30
# stat_type: margin1

# Checkpoints
loss_str: ''
check_path: !ref Data/checkpoint/<model>/<datasets>/<feat_type>_egs<subset>_baseline/<loss>_<optimizer>_<scheduler>/<input_norm>_batch<batch_size>_<encoder_type>_em<embedding_size><loss_str>_wde5_2ses_dist
resume: ''
#  !ref <check_path>/checkpoint_40.pth

veri_pairs: 9600
gpu_id: 0,1


test_interval: 4
log_interval: 10