# @Author: yangwenhao
# @Contact: 874681044@qq.com
# @Software: PyCharm
# @File: vox1_brain_random0.yaml
# @Time: 2024/01/10 14:59
# @Overview:

data_root_dir: /home/yangwenhao/project/lstm_speaker_verification

## Dataset
seed: 123456
datasets: vox1
testset: vox1
feat_type: wave
loss: arcsoft
input_dim: 80
feat: int
wav_type: int
subset: ""
sample_type: instance

train_dir: !ref <data_root_dir>/data/<datasets>/dev
train_test_dir: !ref <data_root_dir>/data/<testset>/test
train_trials_path: !ref <data_root_dir>/data/<testset>/test/trials
train_trials: trials
num_valid: 0.05
test_dir: !ref <data_root_dir>/data/<testset>/test
trials: trials
input_norm: Mean

test_input: fix
log_scale: False
sr: 16000
# transform
chunk_size: 64000

# padding
random_chunk: [32000, 32000]
frame_shift: 48000 # test shift

# train dataset config
num_frames: 64000
segment_shift: 64000

# sample_type: instance
# adaptive_select: True
select_method: muloptimal
adaptive_lr: True
# select_scores: 'max'
# select_sample: ccs
# select_repeat: 2
# optim_times: 1.5
# noise_size: 0.001
# sample_ratio: 0.25
full_epoch: 0
select_epoch: 30
# stratas_select: kmeans

input_per_spks: 768
extract: True
nj: 8
shuffle: False
batch_shuffle: True

feat_format: wav
remove_vad: False

### Training settings
epochs: 30

# optimizer
optimizer: adam
lr_decay: 0
weight_decay: 0.00002
second_wd: 0.0002
dampening: 0
nesterov: False
momentum: 0.9
accu_steps: 1

# Scheduler
scheduler: cyclic
# step_size: 65000
cyclic_epoch: 5
patience: 3
milestones: [10, 20, 30, 40]
val_check_interval: 5994

lr: 0.001
base_lr: 0.00000001
cos_sim: True

# early_stopping: True
# early_patience: 15
# early_delta: 0.001
# early_meta: "mix8"

## model Setttings
model: ECAPA_brain
kernel_size:
alpha: 0
embedding_size: 192
batch_size: 96
dropout_p: 0.0
activation: relu
channels: 512,512,512,512,1536 
#[512, 512, 512, 512, 1536]
#channels: [1024,1024,1024,1024,3072]
encoder_type: "SASP2"
num_classes: 1211

embedding_model: !new:Define_Model.TDNN.ECAPA_brain.ECAPA_TDNN
  filter: "fbank"
  sr: 16000
  feat_dim: !ref <input_dim>
  input_dim: !ref <input_dim>
  input_norm: !ref <input_norm>
  channels: [256, 256, 256, 256, 768]
  encoder_type: "SASP2"
  embedding_size: !ref <embedding_size>
  num_classes: !ref <num_classes>

augment_wavedrop: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
  sample_rate: !ref <sr>
  speeds: [100]

augment_speed: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
  sample_rate: !ref <sr>
  speeds: [95, 100, 105]

# rir_folder: /home/yangwenhao/project/lstm_speaker_verification/data/rir #!ref <data_folder> # Change it if needed
rir_folder: '/data2022/yangwenhao/dataset'
# musan_lst: '/home/yangwenhao/project/SpeakerVerification-pytorch/Misc/audio_processing/musan_4s_nospeech.csv'
add_rev: !new:speechbrain.lobes.augment.EnvCorrupt
   openrir_folder: !ref <rir_folder>
   openrir_max_noise_len: 3.0  # seconds
   reverb_prob: 1.0
   noise_prob: 0.0
   noise_snr_low: 0
   noise_snr_high: 15
   noise_num_workers: 4
   rir_scale_factor: 1.0

add_noise: !new:speechbrain.lobes.augment.EnvCorrupt
   openrir_folder: !ref <rir_folder>
   openrir_max_noise_len: 3.0  # seconds
   reverb_prob: 0.0
   noise_prob: 1.0
   noise_snr_low: 0
   noise_snr_high: 15
   noise_num_workers: 4
   rir_scale_factor: 1.0

add_rev_noise: !new:speechbrain.lobes.augment.EnvCorrupt
   openrir_folder: !ref <rir_folder>
   openrir_max_noise_len: 3.0  # seconds
   reverb_prob: 1.0
   noise_prob: 1.0
   noise_snr_low: 0
   noise_snr_high: 15
   noise_num_workers: 4
   rir_scale_factor: 1.0

augment_pipeline: [
   !ref <augment_wavedrop>,
   !ref <augment_speed>,
   !ref <add_rev>,
   !ref <add_noise>,
   !ref <add_rev_noise>,
]

concat_augment: True
num_pipes: 3

# loss
loss_ratio: 1
lr_ratio: 0
loss_lambda: False
loss_type: !ref <loss>
margin: 0.2
# m: 0.2
s: 30
lamda_beta: 0.2
# mixup_type: input
# stat_type: margin1

# Checkpoints
loss_str: ""
check_path: !ref Data/checkpoint/<model>/<input_norm>_batch<batch_size>_<encoder_type>_em<embedding_size><loss_str>_official_2s/<loss>_<optimizer>_<scheduler>/<datasets>/<feat_type>_fb<input_dim>_inst_aug5<num_pipes>_oneshot_lr

save_data_dir: Data/checkpoint/ECAPA_brain/Mean_batch96_SASP2_em192_official_2s/arcsoft_adam_cyclic/vox1/wave_fb80_inst
select_save_dir: Data/checkpoint/ECAPA_brain/Mean_batch96_SASP2_em192_official_2s/arcsoft_adam_cyclic/vox1/wave_fb80_inst_aug53_oneshot_lr_muloptimal

#_mixup<lamda_beta>_<mixup_type>
resume: !ref <check_path>/checkpoint_40.pth

veri_pairs: 9600
gpu_id: 0,1

test_interval: 4
log_interval: 10
