# @Author: yangwenhao
# @Contact: 874681044@qq.com
# @Software: PyCharm
# @File: aidata_resnet.yaml
# @Time: 2022/09/30 09:15
# @Overview:

data_root_dir: /home/work2020/yangwenhao/project/lstm_speaker_verification

## Dataset
seed: 123456
datasets: vox1
testset: vox1
feat_type: wave
loss: arcsoft
input_dim: 80
feat: int
wav_type: int
subset: ""

train_dir: !ref <data_root_dir>/data/<datasets>/dev
# <subset>_<feat>
train_test_dir: !ref <data_root_dir>/data/<testset>/test<subset>
train_trials_path: !ref <data_root_dir>/data/<testset>/test<subset>/trials

train_trials: trials
valid_dir: !ref <data_root_dir>/data/<datasets>/train_valid_<feat>
num_valid: 2
test_dir: !ref <data_root_dir>/data/<testset>/test
trials: trials
input_norm: Mean
input_per_spks: 512

test_input: fix
log_scale: False
sr: 16000
random_chunk: [48000, 48000]
chunk_size: 48000
frame_shift: 48000
segment_shift: 32000

num_frames: 48000
extract: True
nj: 6
shuffle: False
batch_shuffle: True

feat_format: wav
remove_vad: False

### Training settings
epochs: 60

# optimizer
optimizer: sgd
lr_decay: 0
weight_decay: 0.0005
dampening: 0
nesterov: False
momentum: 0.9
accu_steps: 1

# Scheduler
patience: 4
milestones: [10, 20, 30, 40]
scheduler: rop
lr: 0.1
base_lr: 0.00001
cyclic_epoch: 6
val_check_interval: 1211
cos_sim: True

early_stopping: True
early_patience: 20
early_delta: 0.0001
early_meta: "mix2"

## model Setttings
resnet_size: 18
block_type: "basic"
red_ratio: 2
encoder_type: "SAP2"
downsample: "k3"
model: ThinResNet
kernel_size:
alpha: 0
avg_size: 10
embedding_size: 256
batch_size: 256
dropout_p: 0.1
activation: relu
channels: 32,64,128,256
fast: none1
num_classes: 1211
  # mask: frl

embedding_model: !new:Define_Model.ResNet.ThinResNet
  filter: "fbank"
  sr: 16000
  mask: ftrl
  feat_dim: !ref <input_dim>
  input_dim: !ref <input_dim>
  resnet_size: !ref <resnet_size>
  input_norm: !ref <input_norm>
  block_type: !ref <block_type>
  downsample: !ref <downsample>
  red_ratio: !ref <red_ratio>
  fast: !ref <fast>
  alpha: !ref <alpha>
  kernel_size: [5, 5]
  stride: [2, 1]
  channels: [16, 32, 64, 128]
  dropout_p: !ref <dropout_p>
  avg_size: !ref <avg_size>
  encoder_type: !ref <encoder_type>
  embedding_size: !ref <embedding_size>
  num_classes: !ref <num_classes>
  activation: relu

classifier: !new:Define_Model.Loss.SoftmaxLoss.AdditiveMarginLinear
  feat_dim: !ref <embedding_size>
  num_classes: !ref <num_classes>

# loss
loss_ratio: 1
lr_ratio: 0
loss_lambda: False
loss_type: !ref <loss>
margin: 0.2
# m: 0.2
s: 30
#lamda_beta: 0.2
#mixup_type: input
lamda_beta: 2
proser_gamma: 1
#_<proser_gamma>
mixup_layer: [1, 2, 3]
mixup_type: ""
# stat_type: margin1

# Checkpoints
loss_str: ""
check_path: !ref Data/checkpoint/<model><resnet_size>/<input_norm>_batch<batch_size>_<block_type>_down<downsample>_avg<avg_size>_<encoder_type>_em<embedding_size>_dp01_alpha<alpha>_<fast>_wde4_esmix2/<loss>_<optimizer>_<scheduler>/<datasets>/<feat_type><subset>_fb<input_dim>_dist2_ftrl

save_data_dir: !ref Data/checkpoint/<model><resnet_size>/<input_norm>_batch<batch_size>_<block_type>_down<downsample>_avg<avg_size>_<encoder_type>_em<embedding_size>_dp01_alpha<alpha>_<fast>_wde4_esmix2/<loss>_<optimizer>_<scheduler>/<datasets>/<feat_type><subset>_fb80_dist2
#_lamda<lamda_beta>
#_mixup<lamda_beta>_<mixup_type>
# _red<red_ratio>
resume: !ref <check_path>/checkpoint_17.pth

veri_pairs: 9600
gpu_id: 0,1

test_interval: 1
log_interval: 10
